name: linkerd
services:
  linkerdinstallation:
    type: #$(#use https://raw.githubusercontent.com/service-mesh-patterns/service-mesh-patterns/master/samples/istioinstall.yaml)
    settings: 
        controlplaneNS: linkerd-system
        namespace: default
        linkerdVersion: 2.11.3
        profile: default
  emojivoto:
    type: #$(#use https://raw.githubusercontent.com/service-mesh-patterns/service-mesh-patterns/master/samples/bookInfoNoK8sPattern.yaml)
    settings: 
      namespace: default
    dependsOn:
      - linkerdinstallation